services:
  - type: web
    name: my-node-app
    github:
      branch: main
    env:
      - key: NODE_ENV
        value: production
    buildCommand: npm install && npm run build
    startCommand: npm start